services:
  django:
    build:
      context: ./smdb
      dockerfile: ./compose/debug/django/Dockerfile
      # https://github.com/compose-spec/compose-spec/pull/433/files
      ulimits:
        nofile:
          soft: 1000000
          hard: 1048576
    image: smdb_debug_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      # Edit source path to use directories from *your* host
      - /Users/mccann/docker_smdb_vol/etc:/etc/smdb:z
      - /Users/mccann/.ssh:/root/.ssh:z
      # Mount smb://titan.shore.mbari.org/SeafloorMapping on your Mac
      - /Volumes/SeafloorMapping:/mbari/SeafloorMapping:z
      - .:/app:z
      # Edit source path to use directories from *your* host
      - /Users/mccann/docker_smdb_vol/media_files:/media:z
    env_file:
      # Needed for runtime, add to smdb/.envs/.local/.django:
      # Mac M1/M2:
      #   GEOS_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libgeos_c.so
      #   GDAL_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libgdal.so
      # Intel:
      #   GEOS_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgeos_c.so
      #   GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so
      - ./smdb/.envs/.local/.django
      - ./smdb/.envs/.local/.postgres
    ports:
      # VS Code debug launch uses 8000, command: /start uses 8001
      - "8000:8000"
      - "8001:8001"
    command: /start

  postgres:
    build:
      context: ./smdb
      dockerfile: ./compose/debug/postgres/Dockerfile
    image: smdb_production_postgres
    container_name: postgres
    volumes:
      # Edit source path to use directories from *your* host
      - /Users/mccann/docker_smdb_vol/pg_data:/var/lib/postgresql/data:Z
      - /Users/mccann/docker_smdb_vol/pg_data_backups:/backups:z
    env_file:
      - ./smdb/.envs/.local/.postgres

  mailhog:
    # arm build: https://github.com/mailhog/MailHog/issues/359#issuecomment-1107160980
    image: jcalonso/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"

  mb-system:
    image: mbari/mbsystem:latest
    container_name: mb-system
    volumes:
      # Edit source path to use directories from *your* host
      # Copy your public key to your ~/.ssh/authorized_keys file
      - /Users/mccann/.ssh:/root/.ssh:z
      - /Volumes/SeafloorMapping:/mbari/SeafloorMapping:z
    command: /usr/sbin/sshd -D

  nginx:
    image: smdb_debug_nginx
    build:
      context: ./smdb
      dockerfile: ./compose/debug/nginx/Dockerfile
      args:
        - DOCKER_USER_ID=$DOCKER_USER_ID
    container_name: nginx
    volumes:
      # User with $DOCKER_USER_ID needs read permissions on this share
      - /Volumes/SeafloorMapping:/usr/share/nginx/html/SeafloorMapping:ro
    ports:
      - "80:80"

  # https://github.com/SeleniumHQ/docker-selenium#version-3
  # Open http://localhost:7900/?autoconnect=1&resize=scale&password=secret to monitor browser progress
  chrome:
    image: seleniarm/node-chromium:117.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7900:7900"

  firefox:
    image: seleniarm/node-firefox:117.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: seleniarm/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
