# Generated by Django 4.2.9 on 2026-01-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smdb", "0055_quality_category_remove_mission_status_delete_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="area",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mission",
            name="directory",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
