# Generated by Django 4.2.9 on 2026-01-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smdb", "0056_mission_area_alter_mission_directory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="area",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
