version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/debug/django/Dockerfile
    image: smdb_debug_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    environment:
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=smdb
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=ci_password
      - DATABASE_URL=postgis://ci_user:ci_password@postgres:5432/default
    ports:
      # VS Code debug launch uses 8000, command: /start uses 8001
      - "8000:8000"
      - "8001:8001"
    command: /start
     
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: smdb_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=smdb
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=ci_password
      - DATABASE_URL=postgis://ci_user:ci_password@postgres:5432/default
