version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_media_files: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/debug/django/Dockerfile
    image: smdb_debug_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
      - local_media_files:/media:z
    environment:
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test_default
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=ci_password
      - DATABASE_URL=postgis://ci_user:ci_password@postgres:5432/test_default
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,django
      - DJANGO_SETTINGS_MODULE=config.settings.test
    ports:
      # VS Code debug launch uses 8000, command: /start uses 8001
      - "8000:8000"
      - "8001:8001"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: smdb_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=test_default
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=ci_password
      - DATABASE_URL=postgis://ci_user:ci_password@postgres:5432/test_default

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: smdb_local_node
    container_name: node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"

  # https://github.com/SeleniumHQ/docker-selenium#version-3
  chrome:
    image: selenium/node-chrome:4.2.2-20220609
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      # To monitor: http://localhost:7900/?autoconnect=1&resize=scale&password=secret
      - "7900:7900"

  edge:
    image: selenium/node-edge:4.2.2-20220609
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.2.2-20220609
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.2.2-20220609
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
