version: "3"

# Designed to be executed in Github Actions via .github/workflows/ci.yml
# Can be tested locally with `act -P macos-14=-self-hosted` (https://github.com/nektos/act)

volumes:
  ci_postgres_data: {}
  ci_postgres_data_backups: {}
  ci_media_files: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/ci/django/Dockerfile
    image: smdb_ci_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
      - ci_media_files:/media:z
    environment:
      - USE_DOCKER=yes
      - IPYTHONDIR=/app/.ipython
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=smdb
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=ci_password
      - DATABASE_URL=postgis://ci_user:ci_password@postgres:5432/default
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,django
      - DJANGO_SETTINGS_MODULE=config.settings.test
      - GEOS_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libgeos_c.so
      - GDAL_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/libgdal.so
    ports:
      # VS Code debug launch uses 8000, command: /start uses 8001
      - "8000:8000"
      - "8001:8001"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/debug/postgres/Dockerfile
    image: smdb_ci_postgres
    container_name: postgres
    volumes:
      - ci_postgres_data:/var/lib/postgresql/data:Z
      - ci_postgres_data_backups:/backups:z
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=smdb
      - POSTGRES_USER=ci_user
      - POSTGRES_PASSWORD=ci_password
      - DATABASE_URL=postgis://ci_user:ci_password@postgres:5432/default

  mailhog:
    # arm build: https://github.com/mailhog/MailHog/issues/359#issuecomment-1107160980
    image: jcalonso/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: smdb_ci_node
    container_name: node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"

  # https://github.com/SeleniumHQ/docker-selenium#version-3
  # Open http://localhost:7900/?autoconnect=1&resize=scale&password=secret to monitor browser progress
  chrome:
    image: seleniarm/node-chromium:117.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "7900:7900"

  firefox:
    image: seleniarm/node-firefox:117.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: seleniarm/hub:4.10.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
