version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  local_media_files: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      args:
        - DOCKER_USER_ID=$DOCKER_USER_ID
    image: smdb_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    volumes:
      - /home/docker_user/.ssh:/home/docker_user/.ssh:z
      - /mbari/SeafloorMapping:/mbari/SeafloorMapping:z
      - /opt/docker_smdb_vol:/etc/smdb:z
      - local_media_files:/media:z

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: smdb_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: smdb_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:5.0

  mb-system:
    build:
      # Build image that has user docker_user already added - needed before volume mount
      # Make sure DOCKER_USER_ID is set in the environment before build - see README.md
      context: .
      dockerfile: ./compose/production/mb-system/Dockerfile
      args:
        - DOCKER_USER_ID=$DOCKER_USER_ID
    image: mb-system
    container_name: mb-system
    volumes:
      # Edit source path to use directories from *your* host
      # Copy your public key to your ~/.ssh/authorized_keys file
      - /home/docker_user/.ssh:/home/docker_user/.ssh:z
      - /mbari/SeafloorMapping:/mbari/SeafloorMapping:z
    command: /usr/sbin/sshd -D
