name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

jobs:
  ##linter:
  ##  runs-on: ubuntu-latest
  ##  steps:

  ##    - name: Checkout Code Repository
  ##      uses: actions/checkout@v2

  ##    - name: Set up Python 3.9
  ##      uses: actions/setup-python@v2
  ##      with:
  ##        python-version: 3.9

  # Run all pre-commit hooks on all the files.
  # Getting only staged files can be tricky in case a new PR is opened
  # since the action is run on a branch in detached head state
  ##    - name: Install and Run Pre-commit
  ##      uses: pre-commit/action@v2.0.0

  # With no caching at all the entire ci process takes 4m 30s to complete!
  pytest:
    runs-on: macos-14

    steps:
      # https://stackoverflow.com/a/65346817/1281657
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Install Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.1.0 # defaults to 'latest'
          legacy: true    # will also install in PATH as `docker-compose`

      - name: Build the Stack
        run: docker-compose -f smdb/ci.yml up -d --build

      - name: Run the Migrations
        run: docker-compose -f smdb/ci.yml run --rm django python manage.py migrate

      - name: Load the test fixtures
        run: docker-compose -f smdb/ci.yml run --rm django python manage.py loaddata smdb/fixtures/missions_notes_5.json --settings=config.settings.test

      - name: Run Pytest Tests
        run: docker-compose -f smdb/ci.yml run --rm django pytest -s --cov-report term-missing --cov

      - name: Tear down the Stack
        run: docker-compose -f smdb/ci.yml down
